config/routes.rb
Rails.application.routes.draw do

  resources :contacts, only: [:new, :create, :destroy, :index, :show]
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  get 'sites/server'

  get 'sessions/new'

  resources :users
  resources :posts
  resources :photos, only: [:new, :create]

  root 'posts#index'

  resource :session, only: [:new, :create, :delete]

  get 'signin', to: 'sessions#new'
  get 'contact', to: 'contacts#new', as: 'contactp'
  delete 'signout', to: 'sessions#destroy'

end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  include HTTParty

  before_action :set_contact, only: [:show, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    if not current_user.nil?
      @contacts = Contact.all
    else
      redirect_to create_contant
    end

  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
    if not current_user.nil?
      @contacts = Contact.all
    else
      redirect_to contactp_path
    end
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end


  # POST /contacts
  # POST /contacts.json
  def create
    if verify_google_recaptsha(Rails.application.secrets.recaptsha_secret_key, params['g-recaptcha-response'])
      @contact = Contact.new(contact_params)

      respond_to do |format|
        if @contact.save
          format.html { redirect_to @contact, notice: 'Yhteydenotto lähetetty!.' }
          format.json { render :show, status: :created, location: @contact }
        else
          format.html { render :new }
          format.json { render json: @contact.errors, status: :unprocessable_entity }
        end
      end

    else
      redirect_to contactp_path, alert: 'Botti :('
    end

  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:content, 'g-recaptcha-response')
    end

    def verify_google_recaptsha(private_key, response)
      request = HTTParty.post('https://www.google.com/recaptcha/api/siteverify', :query => {
          "secret" => private_key,
          "response" => response
      }, :headers => {
          'Content-Type' => 'application/json'
      })

      parsed = request.parsed_response
      parsed['success'] == true ? true : false
    end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
<script src="https://www.google.com/recaptcha/api.js" async defer></script>

<%= form_for(contact) do |f| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_area :content, class: 'contact-textarea' %>
  </div>

  <div class="g-recaptcha" data-sitekey="6LdwOywUAAAAALbL9QNhdO6cB1W0fELVFNrpkAFg"></div>

  <div class="actions">
    <%= f.submit 'Lähetä' %>
  </div>
<% end %>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contacts</h1>

<table class="table">
  <thead>
    <tr>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.content %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<h1>Ota yhteyttä</h1>

<p>
  Kysyttävää? Kommentoitavaa? Ota yhteyttä alla olevalla kentällä. Jos haluat vastauksen muistathan liittää mukaan esimerkiksi sähköpostiosoitteesi, niin otamme yhteyttä!
</p>

<%= render 'form', contact: @contact %>

<% if not current_user.nil? %>
<%= link_to 'Back', contacts_path %>
<% end %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @contact.content %>
</p>

<%= link_to 'Back', contacts_path %>