config/routes.rb
Rails.application.routes.draw do

  resources :contacts, only: [:new, :create, :destroy, :index, :show]
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  get 'sites/server'

  get 'sessions/new'

  resources :users
  resources :posts
  resources :photos, only: [:new, :create]

  root 'posts#index'

  resource :session, only: [:new, :create, :delete]

  get 'signin', to: 'sessions#new'
  get 'contact', to: 'contacts#new', as: 'contactp'
  delete 'signout', to: 'sessions#destroy'

end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-dismissible alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Etusivu', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user.nil? %>
          <li><%= link_to 'Hallinta', signin_path %></li>
        <% else %>
            <li><%= link_to 'Yhteydenotot', contacts_path %></li>
            <li><%= link_to 'Käyttäjät', users_path %></li>
            <li><%= link_to 'Kirjaudu ulos', signout_path, method: :delete %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'Palvelin', sites_server_path %></li>
<li><%= link_to 'Ota yhteyttä', contactp_path %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Peanut" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Peanut" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
      <div class="container header-box">
        <h1 class="top-header">PeanutNetworks</h1>
        <p class="description lead">Tähän ehk jotain joskus :D</p>
      </div>
      <div class="container">
        <div class="row">
          <div class="col-sm-8">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
        </div>
      </div>
    </main>
  <footer class="footer">
    &copy; PeanutNetworks 2017
  </footer>
  </body>
</html>